repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff format
        entry: /Users/sitorush/.local/bin/uv run ruff format
        language: system
        types: [python]
      - id: ruff-lint
        name: ruff lint
        entry: /Users/sitorush/.local/bin/uv run ruff check --fix
        language: system
        types: [python]
      - id: mypy
        name: mypy
        entry: /Users/sitorush/.local/bin/uv run mypy src/
        language: system
        types: [python]
        pass_filenames: false
